# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-proto-randrproto

# >> macros
# << macros

Summary:    X.Org X11 Protocol randrproto
Version:    1.4.0
Release:    1
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/randrproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-randrproto.yaml
Provides:   randrproto

%description
This extension defines a protocol for clients to dynamically change X screens,
so as to resize, rotate and reflect the root window of a screen.



%prep
%setup -q -n randrproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/randrproto.pc
%{_includedir}/X11/extensions/randrproto.h
%{_includedir}/X11/extensions/randr.h
%doc %{_datadir}/doc/randrproto
# << files
